<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>favorites-icon</name>
   <tag></tag>
   <elementGuidId>260c0059-90d1-4c93-8f57-22f4c35c981e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//header//button[@type='button'])[4]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
