<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>E2E - MyAccountPage</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient>paul.leroy-ext@aroma-zone.com;</mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9fad39d7-e13b-4bda-8074-230fde302df5</testSuiteGuid>
   <testCaseLink>
      <guid>10cab5d0-0be6-4108-bf7c-35dd88fbd682</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, change and add personal informations and change password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d5042c08-0461-4304-abb1-71b2eadeaf32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, Delivery Address create additional, change default, update, delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4557cc5-b1fd-4879-9e62-9481ed3a6a7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4196df98-764f-4cab-bd24-44b9dd03e886</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>46bd0c6c-d841-424d-ac52-f2b7195b0684</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to Loyalty program page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e10670ab-9fe6-4d34-ab74-028d0b554fd0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to my wishlist page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbc0ac9a-dd8b-41bb-9375-4cd7ce26dddf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b801c853-b712-48f5-81ad-130626c67088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>611f1db3-de52-40b9-9068-d7c69d89ed0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e54c2a1b-cccb-4276-a0a1-0774fa2cdaaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cbfa1aa-d39a-43a1-8670-b41ac48cd04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87ef7a8c-0b22-4234-bac4-f514a96d31e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>01b8c142-bcc5-4d80-b1c2-75fb8a5a3b9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to order history page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>afcb949d-9696-46c1-908b-a38beba8bc9e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to notebook page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
