<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>E2E - checkout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>true</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>a04621e5-2cab-4649-9cd1-af92c2641077</testSuiteGuid>
   <testCaseLink>
      <guid>c5f4b856-2d2f-4d38-8c2d-9efc205e413a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Pay by PayPal with Promo Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f5449e0-4228-4382-a66a-67f5c99aab1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9dc473b-f3a8-4cb4-9e89-4da5ba44e4d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2e4bf9ec-5beb-432c-82e2-b99cf44549da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Pay by PayPal</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c89f46-8f15-4e0c-bb91-bce0686a33cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43ba5e4f-8d57-4826-949f-0f8a0f6a73c0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33fee6aa-b354-4202-9e36-5c70e6a38d1c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Pay by Credit Card with Promo Code</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37d3eab1-2fc0-43ec-8cfb-61f88110754d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2e58b96-bad5-4376-a280-f7991bde018e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Pay by Credit Card - new and saved (multiple cards)</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b052bfd-5f4d-49aa-94fa-e4af3b4d0dcd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4997db26-b216-44fc-8667-998c018dd110</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3cf311a-452b-46d6-a648-d141fec7668c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a260a7b5-f6cd-4ea0-a104-c53baf595ab9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>12c7825e-8840-4456-9e7e-38384865b7b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Pay by Bancontact card - new and saved</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>577f66d0-fd8b-4967-b93a-fd1dd3a8745a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f036a882-9005-415d-9498-01849d411904</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Checkout workflow for existing user</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>db717758-cffc-4bf2-afe6-78d6a6d68262</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Checkout page amounts do not change after refresh</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c35632e1-432b-4501-84c3-b219222fb5fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Edge Case, Pay by 3DS Credit Card selecting delivery before payment module is loaded</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c21cba50-626f-45b3-b1e9-52948d8bd7b1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ced3c103-d205-44d6-a35b-16d136f5691c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Checkout/E2E, Apply and remove Promo Code_new version</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
