<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_additionalRequestForm</name>
   <tag></tag>
   <elementGuidId>f1102cbf-7e4e-4f25-9ea0-382a2e486584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#additionalRequestsClient</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
