<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phoneNumber</name>
   <tag></tag>
   <elementGuidId>9fc66228-def5-490c-8b6e-c17c74d20244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input#mobileNumberClient</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
