<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reviews_Block</name>
   <tag></tag>
   <elementGuidId>c811b232-2baa-4902-8086-fc36476cb4e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;rating-reviews-section-title&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//div[@id=&quot;rating-reviews-section-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
