<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_accept</name>
   <tag></tag>
   <elementGuidId>8552d3c8-b0f5-4974-9c36-f33b62c68ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#axeptio_btn_acceptAll</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'axeptio_btn_acceptAll' and @ref_element = 'Object Repository/AZ/Components/Cookies popup/div_needsclick (shadow root)' and @ref_element_is_shadow_root = 'true']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@aria-label=&quot;Accepter les cookies&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>axeptio_btn_acceptAll</value>
      <webElementGuid>2bb4d14c-74d0-4aab-b345-b1404dfe1217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AZ/Components/Cookies popup/div_needsclick (shadow root)</value>
      <webElementGuid>5f8fae29-d825-47fa-bb46-b210ffa7873f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b0251b90-98b8-4a4f-ae20-3090e74d6a4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
