<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>data-testid='tcs-checkbox'</description>
   <name>span_TCs_checkbox</name>
   <tag></tag>
   <elementGuidId>fc409af2-b40c-4a74-a5c9-6b7fa1df91cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>//label[@for='tos']/preceding::input[@type='checkbox'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
