<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_close</name>
   <tag></tag>
   <elementGuidId>3c9c3434-c6eb-4157-88b1-ee963235c79b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.klaviyo-close-form</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
