<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_headerLogoAZ</name>
   <tag></tag>
   <elementGuidId>8752bcc2-3ac0-420d-ae8a-335ee54c9f23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[aria-label=&quot;Logo&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
