<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_cart_total</name>
   <tag></tag>
   <elementGuidId>ccf15967-69c7-4c17-b227-6639c5d4b995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span[data-testid=&quot;header-cart-total&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
