<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_yesAdult</name>
   <tag></tag>
   <elementGuidId>ccdd4a50-74f1-4231-91a9-fae83a87137e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sq_100i_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
