<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_NoPreference</name>
   <tag></tag>
   <elementGuidId>ea5dd02c-82b4-45a2-aaed-5a4ac960e5bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>[id=&quot;staff-list--1&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;staff-list--1&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
