<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_LastName</name>
   <tag></tag>
   <elementGuidId>b0f72714-ac03-49a5-98f3-c8f1d6b24bc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lastNameClient</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
