<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_mobileClient</name>
   <tag></tag>
   <elementGuidId>9ec218df-e8ce-4c93-85a6-c0c6e93e33d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobileNumberClient</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
