<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_emailClient</name>
   <tag></tag>
   <elementGuidId>3f2a3c82-8e15-4901-9c73-5ad563bac464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailClient</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
