<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_civility</name>
   <tag></tag>
   <elementGuidId>1d168f47-ed27-4255-8ff0-16d94f80d26e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#salutation-select</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
