<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_remove_confirm</name>
   <tag></tag>
   <elementGuidId>cb26a73a-7647-4dc9-a28b-f9a17755a4ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[class*=&quot;disable-confirmation__button--remove&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
