<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cardSecurityCode</name>
   <tag></tag>
   <elementGuidId>feee7974-aa4c-4c0a-b4cf-71ffacdfaeb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[id*='adyen-checkout-encryptedSecurityCode']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/AZ/Pages/CheckoutPage/Payment Method/Saved Payment Method/iframe_cardSecurityCode</value>
      <webElementGuid>a9d892b8-dbd2-4bce-bb20-17064c19d943</webElementGuid>
   </webElementProperties>
</WebElementEntity>
