<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_orderList</name>
   <tag></tag>
   <elementGuidId>f0d69eba-c12b-43a7-a099-41c3383f4e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orders-list</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
