<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>orderDetail_totalAmount</name>
   <tag></tag>
   <elementGuidId>25cb6379-71b3-4c63-90e6-0b6b8e81d111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.total-value</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
