<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>data-testid='login-button'</description>
   <name>button_login</name>
   <tag></tag>
   <elementGuidId>8b83129e-4c8f-47dc-8082-c0d2472c676d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type=&quot;submit&quot;])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(text() = 'Se connecter') or (text() = 'Accedi')]</value>
      <webElementGuid>b53d9f48-fdba-44cc-8730-d1857b98d36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout']/section/div[2]/div/div/div/span/form/button/div/div</value>
      <webElementGuid>e8df38cb-57fa-4598-88cc-a70a2a38cf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Se connecter' or . = 'Se connecter')]</value>
      <webElementGuid>b710f292-0330-4e45-8d8d-f28649e3d1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
