<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regression - Desktop</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9718a05a-b98c-470f-ab75-5b3dddf76f39</testSuiteGuid>
   <testCaseLink>
      <guid>11c7d8a6-7fad-4bd0-8feb-289b76701799</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/HomePage/Smoke, Check that click on every left column button of the hero slider changes main image of the slider</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>373342c1-9bff-4f40-91ab-e8a83fecba29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>879206cf-62a6-42bb-b359-ff4ec57e64d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/HomePage/E2E, Book a workshop</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>35815554-1856-458a-9d68-f34ff9a9b9f9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/HomePage/Smoke, footer Icons Link navigation and content check and Icons Link social networks check</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>472b7fee-c94e-42a1-ba1b-c5d977b921f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/HomePage/Smoke, header our latest news, check link and content page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d24a1e16-90f0-4aa3-9d5f-d7de7cf84f1f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/HomePage/E2E, Search Bar do a research and click</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f0bce4ca-f435-49aa-ad40-ccdd9cf732f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/HomePage/Smoke, Verify Correct URL on AZ logo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8c31670d-0aef-473a-b4b3-2fd86fcefe2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, change and add personal informations and change password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9d4e1d75-361b-47d5-9d59-bd95fb2c82f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, Delivery Address create additional, change default, update, delete</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4557cc5-b1fd-4879-9e62-9481ed3a6a7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4196df98-764f-4cab-bd24-44b9dd03e886</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac4bd419-2f04-4764-955c-8e36a80de1d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to Loyalty program page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>fc6c2575-4db6-4c7d-9e79-fd44bf1b485a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to my wishlist page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbc0ac9a-dd8b-41bb-9375-4cd7ce26dddf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b801c853-b712-48f5-81ad-130626c67088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>611f1db3-de52-40b9-9068-d7c69d89ed0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e54c2a1b-cccb-4276-a0a1-0774fa2cdaaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cbfa1aa-d39a-43a1-8670-b41ac48cd04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87ef7a8c-0b22-4234-bac4-f514a96d31e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf7884bb-01e5-4f9c-8764-ecc585883daf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to notebook page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e200f0d9-036b-4926-a37b-98be5e7111a1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/MyAccountPage/E2E, go to order history page and check wording</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b93b3df7-03c3-45de-90f1-9367284f42bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Registration/E2E, Create account and add default delivery and billing addresses</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbc0ac9a-dd8b-41bb-9375-4cd7ce26dddf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b801c853-b712-48f5-81ad-130626c67088</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>611f1db3-de52-40b9-9068-d7c69d89ed0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e54c2a1b-cccb-4276-a0a1-0774fa2cdaaf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cbfa1aa-d39a-43a1-8670-b41ac48cd04c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87ef7a8c-0b22-4234-bac4-f514a96d31e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f9b1d57-958a-4108-9574-168611834b2a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Surveys/E2E, Hair survey</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f33cf27d-9970-4c71-bcd7-c4597e1ff590</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Surveys/E2E, Skincare survey</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0f20f0c9-7072-4933-8274-0f2ea9bd157d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Login/E2E, login with an account</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>11051547-0bce-44bc-a79a-a7dd105d8bcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Cart/E2E, Access empty cart as logged-in user</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>58458a49-0b24-458b-b5cf-051c8c890c4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Cart/E2E, Access empty cart as not logged-in user</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9addb965-8ae3-4662-9959-3dc1dbe980cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/Cart/E2E, Manage number of items on cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>463b54a1-e678-4f1f-840b-8061769cf263</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/AZ/E2E tests/RLP/AddRecipeToNotebook</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
